LICENSE, build/base/Dockerfile, internal/pkg/printer/printer.go
=> adding PDFtk for merging PDF files < 1.7

build/base/Dockerfile, build/docs/content/04-office.md, docs/index.html, internal/app/api/office.go, internal/pkg/printer/office.go, pkg/client.go, pkg/office.go, pkg/office_test.go
=> removing paper size for Office conversion

internal/pkg/printer/merge.go, internal/pkg/printer/office.go
=> 6.0.4: fixing merge order

build/docs/content/04-html.md, docs/index.html
**Summary**
Fixes some PHP examples to be clearer and uniform with the other ones.
=> [Doc] Fix dest param in PHP examples

internal/app/xhttp/handler.go, internal/pkg/chrome/chrome.go
**Summary**
This PR fixes/implements the following **bugs/features**
**Closing issues**
Fixes https://github.com/thecodingmachine/gotenberg/issues/172
**Checklist**
=> [bugfix/issue-172] fixing health check

build/base/Dockerfile
=> Add missing fonts from 6.4.1

Makefile, build/Dockerfile
=> fix: add latest version of noto color emoji front

Makefile, build/Dockerfile, scripts/release.sh
=> feat: support armhf & i386 architectures

docs/openapi.yaml
As detailed on the website documentation, but not in the openapi spec.
=> chore: add 503 to every endpoint as this is a known error

pkg/modules/api/api.go, pkg/modules/chromium/chromium.go, pkg/modules/chromium/chromium_test.go, pkg/modules/chromium/routes.go, pkg/modules/chromium/routes_test.go, pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/api/api_test.go, pkg/modules/libreoffice/routes.go, pkg/modules/libreoffice/routes_test.go, pkg/modules/pdfengines/pdfengines.go, pkg/modules/pdfengines/pdfengines_test.go, pkg/modules/pdfengines/routes.go, pkg/modules/pdfengines/routes_test.go, pkg/modules/pdftk/pdftk.go, pkg/modules/pdftk/pdftk_test.go, pkg/modules/qpdf/qpdf.go, pkg/modules/qpdf/qpdf_test.go, pkg/modules/webhook/webhook.go
Remove all deprecated stuff (v8).
=> feat: remove deprecated stuff

pkg/gotenberg/supervisor.go, pkg/gotenberg/supervisor_test.go
=> fix(supervisor): if process is already restarting, requeue a task

pkg/gotenberg/supervisor.go, pkg/gotenberg/supervisor_test.go, pkg/modules/chromium/chromium.go, pkg/modules/chromium/routes.go, pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/routes.go
=> feat: enable max queue size for chromium and libreoffice

pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/api/api_test.go
=> feat(libreoffice): add macOS *.pages support

pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/api/api_test.go
this should work as expected... , to relate to #812
=> feat(libreoffice): add macOS *.key support

pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/api/api_test.go, pkg/modules/libreoffice/api/libreoffice.go, pkg/modules/libreoffice/api/mocks.go, pkg/modules/libreoffice/api/mocks_test.go
=> feat(libreoffice): retry on core dumped

pkg/modules/chromium/browser.go, pkg/modules/chromium/browser_test.go, pkg/modules/chromium/chromium.go, pkg/modules/chromium/events.go, pkg/modules/chromium/routes.go, pkg/modules/chromium/routes_test.go
=> fix(chromium): increase the scope of loading failed errors

pkg/modules/api/api.go, pkg/modules/api/api_test.go
=> feat(api): add HEAD method for health route

pkg/modules/webhook/middleware.go
=> fix(webhook): retrieve values from echo.Context before it get recycled

pkg/modules/chromium/browser.go, pkg/modules/chromium/browser_test.go, pkg/modules/chromium/chromium.go, pkg/modules/chromium/events.go, pkg/modules/chromium/routes.go, pkg/modules/chromium/routes_test.go, pkg/modules/chromium/tasks.go
=> feat(chromium): add scope to extraHttpHeaders

pkg/modules/pdfengines/pdfengines_test.go
Apologies, seems I skipped over a typo myself as well.
=> [hotfix] Fix remaining typo on test class

.github/workflows/continuous-integration.yml, build/Dockerfile
=> fix(Dockerfile): use latest Chromium version for armhf

build/Dockerfile, pkg/modules/libreoffice/api/api.go, pkg/modules/libreoffice/api/libreoffice.go, pkg/modules/libreoffice/routes.go
=> feat(libreoffice): add updateIndexes form field

pkg/modules/webhook/middleware.go, test/integration/features/webhook.feature
=> Add support for having sync upload with webhook url

build/Dockerfile
=> fix(Dockerfile): remove upx stage
