app/context/context.go
app/context/context_test.go
app/handlers.go

Improving logging (a little)
**Checklist**

slighty improvement of logging

---

.ci/gotenberg.yml
_tests/configurations/broken-gotenberg.yml
_tests/configurations/duplicate-command-gotenberg.yml
_tests/configurations/gotenberg.yml
_tests/configurations/merge-timeout-gotenberg.yml
_tests/configurations/timeout-gotenberg.yml
_tests/configurations/wrong-command-template-gotenberg.yml
_tests/configurations/wrong-logging-formatter-gotenberg.yml
_tests/configurations/wrong-logging-level-gotenberg.yml
_tests/configurations/wrong-merge-command-template-gotenberg.yml
app/config/config.go
app/config/config_test.go
app/config/parser.go
app/converter/process/process.go
app/converter/process/process_test.go

The new attribut `interpreter` allows user to specify a binary which will call the considered command.
Example:
```yaml
commands:
merge:
template: "pdftk {{ range $filePath := .FilesPaths }} {{ $filePath }} {{ end }} cat output {{ .ResultFilePath }}"
interpreter: "/bin/sh -c"
timeout: 30
```
**Checklist**

new attribute interpreter for commands

---

.ci/gotenberg.yml
_tests/configurations/broken-gotenberg.yml
_tests/configurations/duplicate-command-gotenberg.yml
_tests/configurations/merge-timeout-gotenberg.yml
_tests/configurations/no-lock-gotenberg.yml
_tests/configurations/timeout-gotenberg.yml
_tests/configurations/wrong-command-template-gotenberg.yml
_tests/configurations/wrong-logging-formatter-gotenberg.yml
_tests/configurations/wrong-logging-level-gotenberg.yml
_tests/configurations/wrong-merge-command-template-gotenberg.yml
app/config/config.go
app/config/config_test.go
app/config/parser.go
app/converter/process/process.go
app/converter/process/process_test.go

The new attribute `lock` allows a user to perform concurrent conversions if its current implementation allows it.
Example:
```yaml
commands:
lock: false
merge:
template: "pdftk {{ range $filePath := .FilesPaths }} {{ $filePath }} {{ end }} cat output {{ .ResultFilePath }}"
interpreter: "/bin/sh -c"
timeout: 30
```
**Checklist**

adding new attribute lock

---

internal/app/api/api.go
internal/app/api/api_test.go

Hi!
I need to create a kubernetes pod with gotenberg and there is currently no easy way to set the liveness and readiness probs. In order to solve that issue I propose this ping endpoint which just return a 200 once the API is available.
It can be used to check the service liveness un docker-compose and is very useful for kubernetes (liveness and readiness probs).

Add a /ping endpoint

---

internal/pkg/printer/html.go

**Summary**
Error: `runtime.ExceptionDetails: Uncaught exception at 4:47: SyntaxError: Unexpected token %`
**Closing issues**
Fixes #44
**Checklist**

Fix for #44 promise wait for fonts

---

cmd/gotenberg/main.go

**Summary**
This PR fixes a copy and paste error with the error message. I saw an 
```
error: DEFAULT_WAIT_TIMEOUT: wrong value: want "0" or "1" got true
```
When I should have seen 
```
error: DISABLE_GOOGLE_CHROME: wrong value: want "0" or "1" got true
```
when running gotenberg with `DISABLE_GOOGLE_CHROME=true`

Fix google chrome env var error message

---

build/base/Dockerfile
internal/pkg/pm2/pm2.go

As noted in the Dockerfile, the previous route to install pm2 was broken at
some point. As a result, pm2 related files are now being copied over from an
image created prior to the breakage.
This change now installs pm2 via npm, which is the recommended route for this.
A small adjustment had to be made in the processManager code; an
argument was being passed with a space in it. For reasons that I've not been
able to fully trace, this no longer works. It should be noted that passing
arguments in this way can result in undesirable behaviour - in this case I
believe "--interpreter none" was being passed as a single argument, rather than
"--interpreter", "none". I've adjusted this to use an equals - splitting into 2
separate strings works well too.
Refs #65

Install pm2 via npm

---

build/docs/content/03-environment-variables.md
cmd/gotenberg/main.go
internal/app/api/api.go

This PR closes #74.
I wasn't sure organizationally the best fit in terms of location for the skip function, so I added it into middleware.go with the other middleware functions. 
I also took the opportunity to add the `/ping` endpoint as a constant just to DRY it up a bit. Tested locally and it works as expected.

skip logging when healthcheck url is called

---

build/docs/content/03-environment-variables.md
cmd/gotenberg/main.go
internal/app/api/api.go

This PR adds the ability to configure the port which gotenberg will listen on. Per discussion on #75 I've tried to keep to the environment variable paradigm outlined.
Although I've based this branch off the work on #75, it would be easy enough to separate them out more formally.

Configure listen port via environment variable

---

internal/pkg/pm2/chrome.go

This pull request is about adding additional argument for headless Chrome: **--font-render-hinting medium**, which is required for consistent font rendering. See [this issue](https://github.com/GoogleChrome/puppeteer/issues/2410)
Fonts differs in real Chrome from the ones in generated PDF, unless this option is provided

Inconsistent text rendering in headless mode

---

internal/app/xhttp/handler.go
internal/app/xhttp/handler_test.go
internal/app/xhttp/middleware.go
internal/app/xhttp/xhttp_test.go

Fixes #67.
* Non-existing endpoints now return a `404` HTTP error code instead of `500`
* `405` HTTP error code if wrong method
* `415` HTTP error code if wrong `Content-Type`

improving HTTP error code and fixing #67

---

build/docs/content/03-environment-variables.md
build/package/Dockerfile
docs/index.html
internal/app/xhttp/xhttp.go
internal/app/xhttp/xhttp_test.go
internal/pkg/conf/conf.go
internal/pkg/conf/conf_test.go

**Summary**
This MR adds some changes we have been using internally, in order to add HTTP Basic authentication out-of-the-box.
We know that project's idea about this is that authentication should be provided by external software, but this can be useful in some scenarios, like running on Google Cloud Run.
This PR fixes/implements the following **features**
The main motivation is, as explained above, allowing the container to run standalone in a serverless environment like the ones provided on AWS or GCP.
I have added tests that cover the functionality and this behaviour is configurable by using environment variables.
**Closing issues**
It does not close, but can help to the people watching [this issue](https://github.com/thecodingmachine/gotenberg/issues/90) …

Add basic authentication

---

build/package/Dockerfile

**Summary**
This PR fixes the issue where containers fail to start in Google Cloud Run (and potentially other cloud environments) due to a permission error on container initialization.
N/A
**Closing issues**
Fixes #90

Fix container initialization in Google Cloud Run

---

build/package/Dockerfile

**Summary**
This MR includes a small change to the package docke image to use an statically linked version of tini, so no issues related to updated libraries should arise in the future.
This PR fixes/implements the following **bugs/features**
Building the image and checking that it starts succesfully.
**Checklist**

Use statically linked version of tini

---

internal/pkg/chrome/chrome.go

**Summary**
When using font render hinting on Chrome headless on Linux, the kerning is inconsistent. Several issues cover this, including:
* https://github.com/puppeteer/puppeteer/issues/661
* https://github.com/nzzdev/Q-server/pull/193
Disabling that render hinting entirely results in correct kerning. Related to this is #99, but unfortunately that fix still results in kerning issues.
Here is a PDF using various widths of the Roboto font:
| Before (v6.1.1) | After |
| - | - |
| <img width="917" alt="Screen Shot 2019-12-30 at 8 51 26 PM" src="https://user-images.githubusercontent.com/114033/71610489-632fbf00-2b46-11ea-9560-73c2c638b869.png"> | <img width="913" alt="Screen Shot 2019-12-30 at 8 51 34 PM" src="https://user-images.githubusercontent.com/114033/71610490-632fbf00-2b46-11ea-9fb3-af …

use --font-render-hinting=none to fix kerning

---

build/docs/content/04-html.md
docs/index.html
internal/app/xhttp/option.go
internal/app/xhttp/pkg/resource/arg.go
internal/app/xhttp/pkg/resource/arg_test.go
internal/pkg/printer/chrome.go

**Summary**
This PR fixes/implements the following **feature**:
This came up as part of an unrelated use-case in which the resulting PDF needed to be printed at 85% scale.  I noticed that Gotenberg did not yet support the [PrintToPDFArgs.Scale](https://github.com/mafredri/cdp/blob/master/protocol/page/command.go#L323).  This change implements it as option `scale`.
Output for `make lint tests` is attached: [lint-tests-output.txt](https://github.com/thecodingmachine/gotenberg/files/4143149/lint-tests-output.txt).  One unrelated failure (also in the master branch) occurred.
End-to-end results manually verified in the resulting PDF, but by running the built Docker image with a port-forward:
```curl -XPOST http://localhost:3000/convert/html -H'Content-Type: …
```

Add support for Chrome scaling.

---

docs/index.html

Replaced others with singular form "other"

Fixing documentation typo

---

build/docs/content/03-environment-variables.md
cmd/gotenberg/main.go
docs/index.html
internal/pkg/chrome/chrome.go
internal/pkg/conf/conf.go
internal/pkg/conf/conf_test.go
test/cmd/chrome.go

**Summary**
When using the remote URL conversions feature Chrome will not print when the remote URL provided has certificate errors. Self signed certificates are widely used in dev environments. This PR adds an environment variable that will make the user able to let Chrome ignore those certificate errors. 
This PR fixes/implements the following **features**
Explain the **motivation** for making this change. What existing problem does the pull request solve?
In our dev environment we use this container to print from another locally hosted URL that is secured with a self signed certificate. This PR will help us setup the dev environment as close to production as possible.
The unit tests are extended with a test for this environment variable. For the integration …

Url allow insecure connection

---

docs/index.html

A docker-compose service named "app" will systematically return a blank PDF when using `URLRequest()`.
Added a warning to recommend people to rename their service if it's named "app".

Added warning for URLRequest and service named app

---

build/docs/content/15-links.md
docs/index.html
docs/openapi.yaml

Hi there,
I saw in one of the issues that contributions regarding OpenAPI docs would be welcome, so I went ahead and created one. There are things missing here and there, such as contact information, but I believe this may provide us a basis to improve upon.
You can see the rendered version by copying and pasting the YAML into [Swagger Editor](https://editor.swagger.io/#). It roughly looks like as follows:
I tried to copy the examples and definitions from the existing documentation for consistency.

Add the first version of the OpenAPI documentation

---

build/base/Dockerfile

**Summary**
We are seeing an issue when merging PDFs with Gotenberg, with exceptions coming from `pdftk`.
```
java.lang.ClassCastException: class pdftk.com.lowagie.text.pdf.PRIndirectReference cannot be cast to class pdftk.com.lowagie.text.pdf.PdfName (pdftk.com.lowagie.text.pdf.PRIndirectReference and pdftk.com.lowagie.text.pdf.PdfName are in unnamed module of loader 'app'
```
These issues do not seem to be present in the latest version of `pdftk`. The version currently being used, is quite old, so this patch updates it to the latest version.
**Checklist**

Upgrade PDFtk

---

build/base/Dockerfile

**Summary**
This PR fixes/implements the following **bugs/features**
The image is large, which takes along time to pull, both locally and in CI.
Reducing the image size would speed up all workflows.
before:
```
thecodingmachine/gotenberg   snapshot          6a331ede6633   58 seconds ago   2.09GB
thecodingmachine/gotenberg   workspace         4e672515939a   35 minutes ago   2.57GB
thecodingmachine/gotenberg   base              0283fe0a2587   4 days ago       2.07GB
```
after:
```
thecodingmachine/gotenberg   snapshot          5fb3376d929d   6 minutes ago    1.07GB
thecodingmachine/gotenberg   workspace         ea1fda548f72   56 minutes ago   1.62GB
thecodingmachine/gotenberg   base              beb19c268974   58 minutes ago   1.05GB
```
Existing tests should pass …

Reduce the docker image size

---

build/base/Dockerfile

Changed plain http downloads to https ones.
If it actually IS safe to download these files via plain http, please pardon my ignorance. An explanation would be appreciated. I'm not familiar with the inner workings of `.deb`s / apt, but this doesn't seem right to me.

Dockerfile: Use https everywhere

---

docs/openapi.yaml

**Summary**
This PR fixes/implements the following **features** - this is actually a minor fix (nice to have)
Explain the **motivation** for making this change. What existing problem does the pull request solve?
I wanna use gotenberg as a docker service and make requests from my spring-boot app. I didn't want to write an http client on my own as I saw that you provide an openapi.yaml spec. Thus, I'm using an openapi generator in my application, feeding your app's openapi spec and voila: The java client that I could already use gets automatically generated. The drawback was that the endpoints in the openapi spec didn't provide any `tags` and then the default name for the Java client would have been `DefaultApi`.. that's not intuitive at all. (see the snapshots below)
**BEFORE**
**AFTER**

Add tags on openapi.yaml endpoints

---

pkg/modules/api/middlewares_test.go

- ports between 0 and 1024 can only be used by root in some OS

Only use webhook ports between 1025 and 65536 in tests

---

pkg/modules/api/api.go

Add support for HTTP/2 cleartext (h2c) via a new flag: `--api-http-version`, with possible values of `http1` (default) and `h2c`.
This is needed when running on Cloud Run, as HTTP/1.1 requests are limited to a maximum upload size of 32MB.
It seems that Echo's HTTP/2 server also supports HTTP/1.1, it should be possible to remove the original `a.srv.Start(address)` call and support both. I left both in just to be safe.

Add h2c support

---

Makefile
go.mod
go.sum
pkg/modules/chromium/chromium.go
pkg/modules/chromium/chromium_test.go

Closes #376.
Also:
* Fixe an issue with the `--chromium-user-agent` property; it was not correctly bound internally (sigh).
* Chore: update Go dependencies.

feat: add --chromium-proxy-server property for the Chromium module

---

build/Dockerfile
pkg/modules/qpdf/doc.go
pkg/modules/qpdf/qpdf.go
pkg/modules/qpdf/qpdf_test.go
pkg/standard/imports.go

I never programmed in Go before, so I don't clearly understand what I am doing.
This PR aims to add QPDF as a tool to merge PDFs, because it can deal with invalid PDFs files, which PDFtk can not do.
Also, I think that would be cool if Gotenberg have another tool on it.

feat: add qpdf engine

---

build/Dockerfile

`ttf-wqy-zenhei` is a community-maintained font that only includes a subset of CJK characters, and was last updated 10 years ago.
Noto Sans CJK and Noto Serif CJK (https://github.com/googlefonts/noto-cjk) by Google and Apple are the go-to fonts for compatibility now.

feat: add Noto CJK fonts

---

pkg/modules/webhook/client.go
pkg/modules/webhook/middleware_test.go

As dicussed in https://github.com/gotenberg/gotenberg/issues/550 this change catches an http response code >=400 to ensure it the caller of the send function can handle it (in this case by logging it).

fix(webhook/client): error on http status codes >= 400

---

cmd/gotenberg.go

A second SIGINT forces shutdown, as usual.

Graceful shutdown on SIGINT and SIGTERM

---

build/Dockerfile

Dependabot uses the `org.opencontainers.image.source` label to fetch release notes, changelogs and commit history for docker images as per https://github.blog/changelog/2023-04-13-dependabot-now-supports-fetching-release-notes-and-changelogs-for-docker-images/
The label is also a standard name for opencontainers as per https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

Added org.opencontainers.image.source label to allow dependabot pull release notes

---

go.mod
go.sum
pkg/modules/chromium/browser.go
pkg/modules/chromium/browser_test.go
pkg/modules/chromium/chromium.go
pkg/modules/chromium/routes.go
pkg/modules/chromium/tasks.go
pkg/modules/pdfcpu/pdfcpu.go

New form field `skipNetworkIdleEvent` to drastically improve Chromium conversions speed. It may not be suitable for all HTML documents, as some may not be fully rendered until this event is fired.
Thanks @rreynier!

feat: skip networkIdle event

---

pkg/modules/chromium/routes_test.go
pkg/modules/libreoffice/api/api.go
pkg/modules/libreoffice/api/libreoffice.go
pkg/modules/libreoffice/api/libreoffice_test.go
pkg/modules/libreoffice/pdfengine/pdfengine.go
pkg/modules/libreoffice/routes_test.go
pkg/modules/pdfengines/routes_test.go

Fixes #746.
Long story short, LibreOffice stated that it was producing PDF/A-1a PDF, which was true for simple documents, but most of the time it was actually producing PDF/A-1b. Because of some metadata, some validators were still seeing those as PDF/A-1a compliant, where in fact it was not the case.
⚠️ breaking change

fix(libreoffice): accept PDF/A-1b instead of PDF/A-1a

---

pkg/modules/chromium/browser.go
pkg/modules/chromium/browser_test.go
pkg/modules/chromium/chromium.go
pkg/modules/chromium/events.go
pkg/modules/chromium/routes.go
pkg/modules/chromium/routes_test.go

Closes #613.
Now returns a `409 Conflict` if the HTTP status code from the main page is not acceptable.
The list of invalid status codes is configurable with the new form field `failOnHttpStatusCodes` that takes a JSON string representing an array of int. For instance:
```
curl --request POST \
--url http://localhost:3000/forms/chromium/convert/url \
--form url="https://httpstat.us/400" \
--form 'failOnHttpStatusCodes="[499,599]"' 
```
* A `x99` represents the range between `x00` and `x99` (e.g., `499` means every HTTP status codes between `400` and `499`).
* Default value of `failOnHttpStatusCodes` is `"[499,599]"`.

feat(chromium): return 409 Conflict if HTTP status code from main page is not acceptable

---

Makefile
pkg/modules/chromium/browser.go
pkg/modules/chromium/browser_test.go
pkg/modules/chromium/chromium.go
pkg/modules/chromium/tasks.go

New flags `--chromium-clear-cache` and `--chromium-clear-cookies` (bool, default to `false`).
Respectively clear the cache and cookies between each conversion if set to `true`.

feat(chromium): flags for clearing cache/cookies between each conversion

---

pkg/modules/api/context.go
pkg/modules/libreoffice/routes.go
pkg/modules/libreoffice/routes_test.go

Addresses issue [771](https://github.com/gotenberg/gotenberg/issues/771)
**Why this feature?**
The filenames generated by the `libreoffice/convert` route returns randomly generated UUID filenames that are then archived in a zip file. For example, `document.docx` would then become `9790de13-5754-49db-aaee-51c8d599c0c0.pdf` after conversion.
**Solution**
Preserve the original filenames for conversion. The example file `document.docx` would then become `document.pdf`. This solution also address an edge case where there may be multiple filenames with the same filename but different extensions. `document.doc` and `document.docx` would then become `document.doc.pdf` and `document.docx.pdf`.

feat(libreoffice): preserve filenames for zipped files instead of using randomly generated UUID filenames

---

pkg/modules/chromium/browser_test.go
pkg/modules/chromium/chromium.go
pkg/modules/chromium/routes.go
pkg/modules/chromium/tasks.go

Closes #421.
New form field `singlePage` (bool).
Chromium also outputs tagged PDFs by default now.

feat(chromium): single page PDF

---

pkg/modules/libreoffice/api/api.go
pkg/modules/libreoffice/api/libreoffice.go
pkg/modules/libreoffice/api/libreoffice_test.go
pkg/modules/libreoffice/routes.go

Feel free to just close if not interested in adding this feature.
Exposes libreoffice's ExportFormFields option, defaults to `true` as this is the current behavior.
When set to `false` the output PDF will, instead of having form fields, just have the inputted/selected content of the fields.
For context I have some docx documents with selection fields that becomes pretty ugly in the output PDFs when exported as PDF form fields.

feat(libreoffice): add exportFormFields option

---

pkg/modules/libreoffice/api/api.go
pkg/modules/libreoffice/api/libreoffice.go
pkg/modules/libreoffice/api/libreoffice_test.go
pkg/modules/libreoffice/routes.go

Exposes libreoffice's SinglePageSheets option, defaults to `false` as this is the current behavior. 
Normally libreoffice will take each sheet in a spreadsheet and fit into onto 1 or more A4 pages in the output PDF.
When `SinglePageSheets` is set to `true` libreoffice will instead render the entire spreadsheet as a single page, with the size of the page being whatever fits the content.
This is useful when the output PDF is to be used digitally and not printed to paper.

feat(libreoffice): add singlePageSheets option

---

pkg/modules/logging/logging.go

Time in logs was printed in utc timezone, with this change we can set environment variable TZ=XXX and time is printed in that timezone.

Write log time in local timezone rather than UTC

---

pkg/modules/libreoffice/api/api.go
pkg/modules/libreoffice/api/libreoffice.go
pkg/modules/libreoffice/api/libreoffice_test.go
pkg/modules/libreoffice/routes.go

Allow the specifying of `losslessImageCompression` and `reduceImageResolution` form data items when calling the convert api endpoint (libreoffice)
These correspond to the ReduceImageResolution and UseLosslessCompression command line arguments to libre office

add libre office image options

---

pkg/modules/libreoffice/api/api.go
pkg/modules/libreoffice/api/libreoffice.go
pkg/modules/libreoffice/api/libreoffice_test.go
pkg/modules/libreoffice/routes.go

Hello!
I needed to display comments in a margin... So I decided to add this option to your app.
I think this is a useful one :)
https://help.libreoffice.org/latest/en-US/text/shared/guide/pdf_params.html

ExportNotesInMargin allows to export comments in margin

---

pkg/modules/api/api.go
pkg/modules/api/api_test.go

Fixes #909 
Only restrict modules' routes for now on (e.g., exclude /health and /version routes).

fix(api): basic auth only for modules' routes

---

go.mod

The problem appears when trying to run locally:
```bash
➜  gotenberg git:(main) ✗ go run cmd/gotenberg/main.go
go: downloading go1.23 (darwin/arm64)
go: download go1.23 for darwin/arm64: toolchain not available
```
The change is based on this answer: https://github.com/golang/go/issues/62278#issuecomment-1693538776

fix for go: download go1.23 toolchain not available

---

pkg/modules/chromium/chromium.go
pkg/modules/chromium/routes.go
pkg/modules/chromium/tasks.go

Resolves #1043
Added the option `generateDocumentOutline` for chromium PDF generation. Example usage:
```sh
curl \
--request POST http://localhost:49153/forms/chromium/convert/url \
--form url=https://liquidlearning.vercel.app/pdf/a00Mn00000PmwksIAB \
--form generateDocumentOutline=true \
-o example.pdf
```
Here's the PDF produced when printing the [Mozart Wikipedia Page](https://en.wikipedia.org/wiki/Wolfgang_Amadeus_Mozart?variant=zh-cn#Appearance_and_character)
- [example.pdf](https://github.com/user-attachments/files/17794572/example.pdf)
Key point being the outline generated on the left sidebar (firefox PDF preview):

feat(chromium): add GenerateDocumentOutline option

---

pkg/modules/pdfengines/multi.go
pkg/modules/pdfengines/multi_test.go
pkg/modules/pdfengines/pdfengines.go
pkg/modules/pdfengines/pdfengines_test.go

Small PR to fix both log and code related typos on the word "metadata".

Metadata typos

---

pkg/modules/api/api.go
pkg/modules/api/api_test.go

Added the root route, `/`:
similar to what is present at https://demo.gotenberg.dev:
---
Only a minor issue, but users can get confused if nothing is displayed at the root URL, e.g. in [this comment](https://github.com/coollabsio/coolify/pull/4759#issuecomment-2589839139).
This could occur when someone is trialing the software using a "one-click deploy" feature/template, e.g. offered by Coolify/Dokploy.
Also potentially useful for basic/automatic health-check services that may not use the `/heath` route.
I believe it's not uncommon to avoid having `/` as 404 - e.g. here's what conduit displays at `/`:
---

feat(api): added dummy root route pointing to docs

---

pkg/modules/pdfengines/multi.go

fix(pdfengines): split and read metadata pdf engines calls

---

pkg/modules/logging/logging.go

The new GCP functionality was missing the mapping of severity, time, logger, caller, message and stack trace keys as well as some encoding options specific to structured logging to GCP. 
This PR addresses it based on this issue: https://github.com/uber-go/zap/issues/1095

fix: correctly map GCP structured log keys

---

pkg/modules/webhook/middleware.go

Fixes the spelling of `attachment` in the default content-disposition header in the webhook middleware. Also allows a custom content-disposition to be specified via the extraHttpHeaders.
Closes #1165

fix(webhook): content-disposition header

---

Makefile
cmd/gotenberg.go
test/integration/features/debug.feature

The `BuildDebug` function currently accounts for approximately one-third of the CPU time in the `Run()` function at the start of the Gotenberg service.
By building debug information only when the log level is debug, we can cut cold start times by up to 6-10% for all other cases.
I’ve attached profiling flame graphs that show a reduction in startup time from 3ms to 2ms.
While this 1ms improvement may seem minor, in serverless environments like Cloud Run this could represent 1-3s shaved from the 5-10s startup time required by a typical setup of 1 vCPU/1GB memory. 
With BuildDebug:
Without BuilDebug:

only build debug info when log level is debug

---

test/integration/scenario/containers.go

Spin via testcontainers an integration-tools image with the same targeted platform.
@gulien I am struggling with formatting and linting 😢 
` make lint
golangci-lint run
level=error msg="[linters_context] typechecking error: : # github.com/gotenberg/gotenberg/v8/pkg/gotenberg\npkg\\gotenberg\\cmd.go:30:41: unknown field Setpgid in struct literal of type syscall.SysProcAttr\npkg\\gotenberg\\cmd.go:50:41: unknown field Setpgid in struct literal of type syscall.SysProcAttr\npkg\\gotenberg\\cmd.go:197:17: undefined: syscall.Kill"
0 issues.
make: *** [Makefile:168: lint] Error 7`
Any suggestions?
May you fix and finalize this PR, please?

Use same targeted platform integration-tools image @ integration tests

---

pkg/modules/chromium/browser.go

Chromium 139 is set to deprecate the Swiftshader backend entirely:
https://chromestatus.com/feature/5166674414927872
And 138 doesn't provide fallback without explicitly enabling it, breaking functionality such as WebGL in Gotenberg
Re-enable GPU support to work around this

fix(chromium): Enable GPU support
